services:
  clock-app:
    build: .
    container_name: clock-container
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080
      - PORT=8080
    volumes: []
    networks:
      - clock-network

networks:
  clock-network:
    driver: bridge
